name: chart-library pipeline
trigger:
  branches:
    include:
      - refs/tags/*
pr:
  branches:
    include:
      - '*'
resources:
  repositories:
    - repository: cnp-azuredevops-libraries
      type: github
      ref: refs/heads/dtspo-34311-upgrade-helm-validation-pl-v4
      name: hmcts/cnp-azuredevops-libraries
      endpoint: 'hmcts'

variables:
  - name: agentPool
    value: ubuntu-latest

jobs:
  - job: Validate
    pool:
      vmImage: ${{ variables.agentPool }}
    steps:
      - template: steps/set-build-repo-suffix-env-var.yaml@cnp-azuredevops-libraries
      - task: HelmInstaller@1
        displayName: 'Install Helm'
        inputs:
          helmVersionToInstall: 4.2.4
      - template: steps/charts/chart-tests.yaml@cnp-azuredevops-libraries
        parameters:
          valuesFile: "ci-values.yaml"
          runSnapshotTests: true
          helmUnittestValuesFiles:
            - "ci-values-minimal.yaml"
            - "ci-values-lang.yaml"
          runUnitTests: true
          chartType: "library"
  - job: Release_Sbox
    condition: >
      and(
          succeeded(),
          startsWith(variables['Build.SourceBranch'], 'refs/tags/')
        )
    dependsOn: Validate
    pool:
      vmImage: ${{ variables.agentPool }}
    steps:
      - template: steps/charts/release.yaml@cnp-azuredevops-libraries
        parameters:
          chartName: library
          chartReleaseName: chart-library
          chartNamespace: chart-tests
          acrName: hmctssbox
          registryServiceConnection: azurerm-sandbox

  - job: Release
    # Make sure we have a tag to run this job
    condition: >
      and(
          succeeded(),
          startsWith(variables['Build.SourceBranch'], 'refs/tags/')
        )
    dependsOn: Validate
    pool:
      vmImage: ${{ variables.agentPool }}
    steps:
      - template: steps/charts/release.yaml@cnp-azuredevops-libraries
        parameters:
          chartName: library
          chartReleaseName: chart-library
          chartNamespace: chart-tests
