name: chart-library pipeline
trigger:
  branches:
    include:
      - refs/tags/*
pr:
  branches:
    include:
      - '*'
resources:
  repositories:
    - repository: cnp-azuredevops-libraries
      type: github
      ref: refs/heads/master
      name: hmcts/cnp-azuredevops-libraries
      endpoint: 'hmcts'

variables:
  - name: agentPool
    value: ubuntu-latest


jobs:
  - job: Validate
    pool:
      vmImage: ${{ variables.agentPool }}
    steps:
      - task: HelmInstaller@1
        displayName: 'Install Helm'
        inputs:
          helmVersionToInstall: 3.12.0
      - script: helm plugin install https://github.com/helm-unittest/helm-unittest.git
        displayName: 'Install Helm Unit Test Plugin'
      - script: sudo snap install yq
        displayName: 'Install yq'
      - script: ./tests/test-templates.sh
        displayName: 'Run unit tests'
  - job: Release
    # Make sure we have a tag to run this job
    condition: >
      and(
          succeeded(),
          startsWith(variables['Build.SourceBranch'], 'refs/tags/')
        )
    dependsOn: Validate
    pool:
      vmImage: ${{ variables.agentPool }}
    steps:
      - template: steps/charts/release.yaml@cnp-azuredevops-libraries
        parameters:
          chartName: library
          chartReleaseName: chart-library
          chartNamespace: chart-tests