applicationPort: 3000
registerAdditionalDns:
  enabled: false
memoryRequests: 64Mi
cpuRequests: 25m
memoryLimits: 512Mi
cpuLimits: 500m
readinessPath: /health
readinessDelay: 5
readinessTimeout: 3
readinessPeriod: 15
livenessDelay: 5
livenessTimeout: 3
livenessPeriod: 15
livenessFailureThreshold: 3
startupDelay: 5
startupTimeout: 3
startupPeriod: 15
startupFailureThreshold: 3
dnsConfig:
  ndots: "3"
pdb:
  enabled: true
  maxUnavailable: 50%
prometheus:
  enabled: false
  path: /metrics
ingressClass: traefik
useWorkloadIdentity: false
global:
  tenantId: "531ff96d-0ae9-462a-8d2d-bec7c0b42082"
  environment: aat
  enableKeyVaults: true
  devMode: false
  smoketestscron:
    enabled: true
  functionaltestscron:
    enabled: true
image: hmctspublic.azurecr.io/chart-nodejs/testapp
replicas: 2
useInterpodAntiAffinity: true
ingressHost: "{{.Release.Name}}.service.core-compute-preview.internal"
disableTraefikTls: true
livenessPath: /health/liveness
startupPath: /health/liveness
imagePullPolicy: Always
environment:
  REFORM_TEAM: cnp
  REFORM_SERVICE_NAME: rhubarb-frontend
  REFORM_ENVIRONMENT: preview
configmap:
  VAR_A: VALUE_A
  VAR_B: VALUE_B
saEnabled: true
envFromSecret: "env-secret"
keyVaults:
  bulk-scan:
    excludeEnvironmentSuffix: false
    secrets:
      - name: idam-client-secret
        alias: idam.client.secret
      - name: s2s-secret
      - name: idam-client-<ENV>-secret
        alias: idam.client.env.secret
      - name: s2s-<ENV>-secret
    certs:
      - name: idam-client-cert
        alias: idam.client.cert
      - name: s2s-cert
  bulk-scan-v2:
    mountPath: /run/secrets/bulk-scan-alias
    excludeEnvironmentSuffix: false
    secrets:
      - name: alias-secret
additionalPathBasedRoutes:
  "/test": "{{.Release.Name}}"
secrets:
  STORAGE_ACCOUNT_NAME:
    secretRef: storage-secret-example-{{ .Release.Name }}
    key: storageAccountName
# WARNING: ingressSessionAffinity is a temporary option.
# This is subject to removal without notice. Do NOT use for any reason!
ingressSessionAffinity:
  enabled: false
  sessionCookieName: sticky

testsConfig:
  memoryRequests: "256Mi"
  cpuRequests: "100m"
  memoryLimits: "2048Mi"
  cpuLimits: "1000m"
  serviceAccountName: tests-service-account
  keyVaults:
    bulk-scan:
      excludeEnvironmentSuffix: true
      secrets:
        - name: idam-client-secret
          alias: IDAM_CLIENT_SECRET
        - name: s2s-secret
        - name: idam-client-<ENV>-secret
          alias: idam.client.env.secret
        - name: s2s-<ENV>-secret
      certs:
        - name: idam-client-cert
          alias: IDAM_CLIENT_CERT
        - name: s2s-cert
smoketests:
  image: hmctspublic.azurecr.io/spring-boot/template
  enabled: false
functionaltests:
  image: hmctspublic.azurecr.io/spring-boot/template
  enabled: false
smoketestscron:
  image: hmctspublic.azurecr.io/spring-boot/template
  enabled: false
  schedule: "20 0/1 * * *"
functionaltestscron:
  image: hmctspublic.azurecr.io/spring-boot/template
  enabled: true
  schedule: "30 0/6 * * *"

# HPA
autoscaling:
  enabled: true
  maxReplicas: 5
  cpu:
    enabled: true
    averageUtilization: 80
  memory:
    enabled: true
    averageUtilization: 80

args:
  - this
  - that
command:
  - this
  - that

additionalIngressHosts: ["{{ .Release.Name }}-ci-01.platform.hmcts.net", "ci-02.platform.hmcts.net"]