---
# Source: library/templates/deployment-tests.yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: release-name-functionaltestscron-job
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: release-name-functionaltestscron
    helm.sh/chart: library-0.1.0
    app.kubernetes.io/name: release-name-library-functionaltestscron
spec:
  schedule: "30 0/6 * * *"
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        metadata:
          labels:
            app.kubernetes.io/name: release-name-library-functionaltestscron
        spec:
          
          volumes:
          - name: vault-bulk-scan
            csi:
              driver: "secrets-store.csi.k8s.io"
              readOnly: true
              volumeAttributes:
                secretProviderClass: release-name-library-tests-bulk-scan
          securityContext:
            runAsUser: 1000
            fsGroup: 1000
          restartPolicy: Never
          serviceAccountName: tests-service-account
          containers:
            - name: tests
              image: hmctspublic.azurecr.io/spring-boot/template
              args: ["IDAM_CLIENT_SECRET=/mnt/secrets/bulk-scan/IDAM_CLIENT_SECRET","S2S_SECRET=/mnt/secrets/bulk-scan/s2s-secret"]
              securityContext:
                allowPrivilegeEscalation: false
              volumeMounts:
              - name: vault-bulk-scan
                mountPath: /mnt/secrets/bulk-scan
                readOnly: true
              resources:
                requests:
                  memory: "256Mi"
                  cpu: "100m"
                limits:
                  memory: "2048Mi"
                  cpu: "1000m"
