# Fed into: helm-unittest assertion tests (tests/unit-tests/conditional/)
image: hmctspublic.azurecr.io/test/app:latest # only required field; set: in each test controls all other inputs
global:
  devMode: false # prevents dev-only resource rendering
  enableKeyVaults: false # prevents KeyVault sidecar injection
